### ISSUE TITLE
使用server bundle时提示window不存在

### ISSUE THREAD

**Issue by FlynnLeeGit** [yyx990803/vue-ssr-demo#3]
client的打包文件ok ，我是通过vueloader 9和webpack打包的，现在只要vue组件含有window或者document时server bundle打包时会将window 和document 一起构建进去，导致node server无法执行

**Comment by yyx990803** [comment]
同构的代码当然不能用 `window` 和 `document`。只有在 `mounted` 钩子里面可以用。

**Comment by FlynnLeeGit** [comment]
好的 谢谢 忘了是virtual dom了 在created里用了 


From m2 note

-------- Original message --------
Sender: Evan You <notifications@github.com>
Time: Mon 7/11 22:14
To: yyx990803/vue-ssr-demo <vue-ssr-demo@noreply.github.com>
Cc: Flynn Lee <cjbfx12345@qq.com>,Author <author@noreply.github.com>
 Subject: Re: [yyx990803/vue-ssr-demo] 使用server bundle时提示window不存在 (#3)
